version: '3.8'

services:
  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - microservices-net

  # User Service
  user-app:
    build: ./backend/user-service
    container_name: user-service-app
    volumes:
      - ./backend/user-service:/var/www
    networks:
      - microservices-net
    depends_on:
      user-db:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  user-web:
    image: nginx:stable-alpine
    container_name: user-service-nginx
    ports:
      - "8001:80"
    volumes:
      - ./backend/user-service:/var/www
      - ./backend/user-service/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - microservices-net
    depends_on:
      - user-app

  user-db:
    image: mysql:8.0
    container_name: user-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_service_db
    ports:
      - "3307:3306"
    volumes:
      - user-data:/var/lib/mysql
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Order Service
  order-app:
    build: ./backend/order-service
    container_name: order-service-app
    volumes:
      - ./backend/order-service:/var/www
    networks:
      - microservices-net
    depends_on:
      order-db:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  order-web:
    image: nginx:stable-alpine
    container_name: order-service-nginx
    ports:
      - "8002:80"
    volumes:
      - ./backend/order-service:/var/www
      - ./backend/order-service/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - microservices-net
    depends_on:
      - order-app

  order-db:
    image: mysql:8.0
    container_name: order-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_service_db
    ports:
      - "3308:3306"
    volumes:
      - order-data:/var/lib/mysql
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Product Service
  product-app:
    build: ./backend/product-service
    container_name: product-service-app
    volumes:
      - ./backend/product-service:/var/www
    networks:
      - microservices-net
    depends_on:
      product-db:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  product-web:
    image: nginx:stable-alpine
    container_name: product-service-nginx
    ports:
      - "8003:80"
    volumes:
      - ./backend/product-service:/var/www
      - ./backend/product-service/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - microservices-net
    depends_on:
      - product-app

  product-db:
    image: mysql:8.0
    container_name: product-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_service_db
    ports:
      - "3309:3306"
    volumes:
      - product-data:/var/lib/mysql
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Frontend Service
  frontend-app:
    build: ./frontend
    container_name: frontend-app
    volumes:
      - ./frontend:/var/www
    networks:
      - microservices-net

  frontend-web:
    image: nginx:stable-alpine
    container_name: frontend-nginx
    ports:
      - "8000:80"
    volumes:
      - ./frontend:/var/www
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - microservices-net
    depends_on:
      - frontend-app

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOSTS: user-db,order-db,product-db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - user-db
      - order-db
      - product-db
    networks:
      - microservices-net

volumes:
  user-data:
  order-data:
  product-data:
  rabbitmq_data:

networks:
  microservices-net:
    driver: bridge
